name: servant-serialization
description: Servant content types and instances for common serialization formats.
version: 0.2.0
license: MIT
maintainer: recurse.social/@redmp
category: Serialization, Servant
extra-source-files: CHANGELOG.md
bug-reports: github.com/plredmond/servant-serialization/issues

dependencies:
  - base >= 4.15 && < 4.17
  - bytestring
  # web libraries
  - servant
  - http-media
  # serialization libraries
  - text # serialization of unicode to utf8 bytestrings
  - binary
  - cereal
  - serialise
  - persist
  - flat

ghc-options:
  - -Wall

library:
    source-dirs: lib

executables:
    example:
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - servant-serialization
            - http-client
            - servant-client
            - http-api-data
            - servant-server
            - QuickCheck
            - warp
            - bytestring
            - aeson

tests:
    doctest:
        main: Doctests.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - servant-serialization
            - doctest
            - QuickCheck
