name: servant-serialization
description: Servant content types and instances for common serialization formats.

dependencies:
  - base
  # web libraries
  - servant
  - http-api-data
  - http-media
  # serialization libraries
  - text # serialization of unicode to utf8 bytestrings
  - binary
  - cereal
  - serialise
  - persist
  - flat

ghc-options:
  - -Wall

library:
    source-dirs: lib

executables:
    example:
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - servant-serialization
            - servant-client
            - servant-server
            - warp
            - bytestring
            - aeson

tests:
    doctest:
        main: Doctests.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - servant-serialization
            - doctest
            - QuickCheck
